# PRIMER AVANCE DEL PÍA

**Equipo:** 8

**Grupo:** 002 (Miercoles 7-10 pm)

**Integrantes:**

* 1872932 Huerta Torres Daniela Paola 

* 1855188 Aguilar Ortiz Verónica Vanessa  

* 1751125 Rodríguez Chaires Fernando Jahir  

* 1857876 Jalomo Hernández Miguel Ángel

## BASE DE DATOS SECUNDARIA

* **Nombre:** Conjunto de datos de predicción de accidentes cerebrovasculares
* **URL:** https://www.kaggle.com/fedesoriano/stroke-prediction-dataset/tasks?taskId=3281

### Introducción
Según la Organización Mundial de la Salud (OMS), el accidente cerebrovascular es la segunda causa principal de muerte a nivel mundial, responsable de aproximadamente el 11% del total de muertes, los que sobreviven corren el riesgo de contar con alguna anomalía como lo es problemas emocionales, problemas del habla, paralitica, perdida de memoria, etc. 

Existen varias formas de advertir que se esta sufriendo un accidente cerebrovascular. En la base de datos, cada fila y columna proporciona información relevante sobre el tipo de paciente que cuenta con este problema.

Este conjunto de datos se utiliza para predecir si es probable que un paciente sufra un accidente cerebrovascular en función de los parámetros de entrada como el sexo, edad, enfermedades, tabaquismo, etc. La mayoría de los accidentes cerebrovasculares se producen en personas de mayor edad, y la mayoría ocurre sin advertencia previa.

### Descripción de datos
* **Id:** Identificación única.
* **Género:** Masculino, Femenino u otro.
* **Edad:** Edad del paciente.
* **Característica binaria de hipertensión:** Si el paciente cuenta con hipertensión = 1, si no cuenta con hipertensión = 0.
* **Característica binaria de enfermedad cardíaca:** Si el paciente cuenta con una enfermedad cardíaca = 1, si el paciente no cuenta con una enfermedad cardíaca = 0.
* **¿El paciente ha estado casado alguna vez?:** Estatus marital (cierto u falso).
* **Tipo de trabajo del paciente:** Tipo de empleo (Privado, Cuenta propia, etc.)
* **Tipo de residencia del paciente:** Rural o Urbano.
* **Nivel medio de glucosa en sangre:** Nivel medio de glucosa en sangre de una persona.
* **Índice de masa corporal:** Índice de masa corporal de una persona.

### Justificación de datos
• **¿Por qué trabajar con ellos?**
Los accidentes cerebrovasculares son muy importantes, y es oportuno saber anticipadamente si estos se pueden prevenir, por lo que, en base a la investigación del tema y los datos proporcionados por la base de datos, con este tipo de información nos podemos enfocar en que tipo de personas en base a la edad, genero y el tipo de residencia es la que es mas predecible que sufra una lesión cerebrovascular y así anticiparnos a la causa.

• **¿Qué beneficio obtenemos al trabajar con estos datos?**
Se puede apreciar que tipo de pacientes son los que comúnmente tienden a tener un problema cerebrovascular en base a sectores como lo son la edad, el genero, tipo de residencia y así como saber si el que tenga otras enfermedades tenga que ver con la causa del problema cerebrovascular, o descartar datos que nos lleven a la causa misma.

### Objetivo final
Realizar una predicción de los accidentes cardiovasculares en cualquier momento de la vida de una persona.

### Preguntas de interés
•	¿En qué rango de edades es más propenso que las personas sufran un accidente cerebrovascular?

•	¿Qué sexo es el mas común en sufrir un accidente cerebrovascular?


•	En base a la información del tabaquismo ¿Es importante enfocarnos primero en las personas que fuman o no lo es?

•	¿Una persona que fuma es igual de propensa a tener una enfermedad cerebrovascular que una que no fuma?


•	¿Por qué los pacientes con residencia Rural tienen casi el mismo porcentaje de accidentes cerebrovasculares que los pacientes con Residencia Urbana?

In [2]:
import pandas as pd
import numpy as np
import json
df = pd.read_csv("C:/Users/Daniela/Desktop/Daniela/Facultad/7mo sem/Mineria/AVANCE PIA/BASE 2/healthcare-dataset-stroke-data.csv")

In [6]:
print("La base de datos original es:")
df

La base de datos original es:

,ID,Sexo,Edad,Hipertensión,Enfermo del corazon,ever_married,work_type,Residence_type,Nivel de glucosa,IMC,Estado respecto a si fuma,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

Para el enfoque que le queremos dar a nuestra investigación. decidimos dejar las columnas que nosotros pensamos que mas influyen al diagnosticar un problema cerebrovascular, como lo es la edad, la hipertensión y estar enfermo del corazón. Tambien se nos hizo interesante dejar del sexo para hacer un estudio de ambos y ver a que población afecta más.

In [4]:
df.rename(columns={'id':'ID','gender':'Sexo','age':'Edad','hypertension':'Hipertensión','heart_disease':'Enfermo del corazon','avg_glucose_level':'Nivel de glucosa','bmi':'IMC','smoking_status':"Estado respecto a si fuma"},inplace=True)
#Modifica los nombres de las columnas, con ayuda de: https://www.analyticslane.com/2019/05/06/como-cambiar-el-nombre-de-las-columnas-en-pandas/
cf=df.drop(['ever_married','work_type','Residence_type','stroke'],axis=1) #Guarda la base que necesitamos en otra variable
#Con ayuda de: https://www.analyticslane.com/2019/03/25/como-eliminar-columnas-y-filas-en-un-dataframe-pandas/

In [5]:
cf

,ID,Sexo,Edad,Hipertensión,Enfermo del corazon,Nivel de glucosa,IMC,Estado respecto a si fuma
0,9046,Male,67.0,0,1,228.69,36.6,formerly smoked
1,51676,Female,61.0,0,0,202.21,NaN,never smoked
2,31112,Male,80.0,0,1,105.92,32.5,never smoked
3,60182,Female,49.0,0,0,171.23,34.4,smokes
4,1665,Female,79.0,1,0,174.12,24.0,never smoked
...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,83.75,NaN,never smoked
5106,44873,Female,81.0,0,0,125.20,40.0,never smoked
5107,19723,Female,35.0,0,0,82.99,30.6,never smoked
5108,37544,Male,51.0,0,0,166.29,25.6,formerly smoked
5109,44679,Female,44.0,0,0,85.28,26.2,Unknown

In [7]:
#Los datos nulos se encuentran en la columna de IMC
df.isnull().any()

ID                           False
Sexo                         False
Edad                         False
Hipertensión                 False
Enfermo del corazon          False
ever_married                 False
work_type                    False
Residence_type               False
Nivel de glucosa             False
IMC                           True
Estado respecto a si fuma    False
stroke                       False
dtype: bool

In [27]:
#En la base de datos hay un total de 201 datos nulos
cf.isnull().sum()

ID                             0
Sexo                           0
Edad                           0
Hipertension                   0
Enfermo del corazon            0
Nivel de glucosa               0
IMC                          201
Estado respecto a si fuma      0
dtype: int64

In [34]:
cf['IMC'].fillna(0,inplace=True)

In [28]:
cf.to_csv("NuevaBaseCerebrovascular.csv",index=False)
#Lugar donde obtuvimos la ayuda: https://aprendeia.com/limpieza-y-procesamiento-de-datos-con-codigo-en-python/